### ISSUE TITLE
🚀 [feature] 알림톡

### ISSUE THREAD

**Issue by cofls6581** [Gosrock/DuDoong-Backend#229]
# 🤖 기능 개요

카카오톡 알림톡 기능 개발
어느 상황에서 알림톡 보낼건지 논의 필요

### ✅ Implement TODO

- [x] spotless
- [x] 전화번호 널처리
- [x] 에러 이셉션 throw
- [x] 전화번호 새로운 양식 머지되면 적용
- [ ] 두둥 새로운 등록 정보로 변경
- [x] 두둥 새로운 템플릿 등록

**Comment by ImNM** [comment]
제휴가 된 호스트일경우 
해당 이벤트 티켓 발급되면 구매자한테 카톡알림

**Comment by ImNM** [comment]
회원가입
약간 카카오톡 플러스 친구 인사하는 형식?

**Comment by ImNM** [comment]
제휴가 된 호스트일경우
주문 취소시..?
