### ISSUE TITLE
도메인 이벤트 정리

### ISSUE THREAD

**Issue by ImNM** [Gosrock/DuDoong-Backend#268]
# 🤖 기능 개요

### ✅ Implement TODO

- [ ]

**Comment by ImNM** [comment]
이미 있는것들
## 유저
- 유저 생성 ( 회원가입 ) 이벤트

## 주문 
- 주문 생성시 이벤트
 -> 승인 주문일 경우 호스트 관리자한테 알림가면 좋을듯!
- 주문 완료시 이벤트
 -> 호스트 관리자한테 슬랙알림 주기? 들어가면 좋을듯!
- 주문 철회시 이벤트
---
추가 될만한 것들?
## 장바구니
- 장바구니 아이템 담았을 때?
## 티켓
- 티켓 아이템이 추가 되었을 때?
- 티켓 아이템이 소진되었을 때..

**Comment by cofls6581** [comment]
## 쿠폰
- 쿠폰 캠페인 생성시 이벤트 (우리한테 알림)
- 생성한 쿠폰 모두 소진시 이벤트 (우리한테 알림, 필수는 x)
- 쿠폰 상태 변경 (우리한테 알림, 오픈클로즈, 필수는 x )

**Comment by sanbonai06** [comment]
## 발급 티켓
- 발급된 티켓 입장 처리 이벤트 (호스트와 유저 모두?)

**Comment by gengminy** [comment]
## 호스트
### 알림
- 호스트에 초대받음
- 호스트 유저 가입 시 (날짜 단위로 ~~님 외 N명이 호스트에 새로 가입했다)
- 호스트 유저 권한 변경
- 마스터 호스트 변경
- 호스트 추방
### 이메일
- 호스트 유저 초대시 이메일
- 마스터 호스트 권한 받았을 때 + 마스터 호스트 변경되었을 때
- 호스트 추방

## 이벤트
### 알림
- 새로운 이벤트 생성
- 이벤트 상태 변경 (오픈 클로즈 등)
- 이벤트 내용 수정됨?
- 이벤트 삭제
